name: CI

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun i --frozen-lockfile
      - run: bunx nx run-many -t lint test typecheck
      - run: bunx nx build desktop --configuration=dev
